### PR TITLE
New Farm Dungeon + new mobs

### PR DESCRIPTION
**Pull request by Simisays**
1. New Farm dungeon 
image

2. New mobs: Insect, horse, gorilla, Scarecrow, boar, chicken and bull. 
3. Fixed collision of the "Merfolk Pool" dungeons
4. Populated the empty grove map 
5. Small fixes of previous PR's

### CODE REVIEW

**Comment by kevlahnota** [comment]
I'm looking at the spritesheet since most of them are not centered, does it have correct collision if the player collide on the top of the sprite? look at the chicken spritesheet, I edited the slime spritesheet before, adjust the size and location of each sprite.

**Comment by Simisays** [comment]
@kevlahnota Do you mean removing the unused white spaces ? I've tested the sprites and the colission seems ok for me

**Comment by kevlahnota** [comment]
> @kevlahnota Do you mean removing the unused white spaces ? I've tested the sprites and the colission seems ok for me. The chicken is just for the new dungeon (same with the gorilla)

No, i mean the extra spaces above each sprites. If you collide with the enemy from the top (player is on top of the enemy moving downwards), do the player and enemy collide visually? Or there is some gap? There should be minimal gap so they don't look too far from each other before the match starts

**Comment by Simisays** [comment]
Updated and tested all the sprites. reduced the size of the walk and idle animation by reducing the emty pixels

**Review by kevlahnota — APPROVED** [review]

**Pull request merged**
