### PR TITLE
Allow backgrounds in Tiny Leaders.

### PR DESCRIPTION
**Pull request by asvitkine**

### CODE REVIEW

**Comment by Hanmac** [comment]
is there a rules that allows Background? because Tiny Leader didn't updated the rules in eons. (that's why Tiny Leaders still has old death replacement)

**Comment by asvitkine** [comment]
> is there a rules that allows Background? because Tiny Leader didn't updated the rules in eons. (that's why Tiny Leaders still has old death replacement)

The current ruleset that's played is TLR (Tiny Leaders Reborn), which does allow backgrounds:
https://tiny-leaders-reborn.blogspot.com/

TL ruleset indeed isn't maintained, so that's not what people play right now. If you're interested, there's a Discord on TLR and there are active tournaments (online and in paper) that are using the format. A number of decklist include a background.

Note: Forge doesn't quite support the TLR ruleset - for example, life total is now 20, not 25. I've been thinking of adding an extra options panel during game set up to allow setting that up - or we could just rename TL to TLR and just set up the defaults - but that's a change for another day.

**Comment by Hanmac** [comment]
> Unfortunately, this fusion project between Original Tiny Leaders and Tiny Leaders Reborn has failed. 

Thats why TLR should be an extra Format and handled separately in Forge

**Comment by asvitkine** [comment]
> > Unfortunately, this fusion project between Original Tiny Leaders and Tiny Leaders Reborn has failed.
> 
> Thats why TLR should be an extra Format and handled separately in Forge

Should it? If TLR is the one that's actually played, why not replace TL with TLR instead of supporting both?

**Comment by Hanmac** [comment]
> > > Unfortunately, this fusion project between Original Tiny Leaders and Tiny Leaders Reborn has failed.
> > 
> > 
> > Thats why TLR should be an extra Format and handled separately in Forge
> 
> Should it? If TLR is the one that's actually played, why not replace TL with TLR instead of supporting both?

because the rules of them are too different, i mean we could change TL into TLR, but that must be cleared with the others.

also for your Background thing, do you know that your Background will be useless most of the time?

> 904.7a: A player using more than 1 commander may only cast one of their commanders from the command zone. This restriction is determined as one of the commanders is cast for the first time in a game and resets between games. For the duration of the game, any other commanders can not be cast from the command zone, but may be cast from other zones (such as the hand).

Meaning if you would cast your Background you can't cast your "Choose a Background" Commander.
And your Background on the Field would do nothing because it only works on Commander Creatures.

**Comment by asvitkine** [comment]
> Meaning if you would cast your Background you can't cast your "Choose a Background" Commander. And your Background on the Field would do nothing because it only works on Commander Creatures.

Indeed, that's true and the TLR committee is evaluating how to evolve that rule. In the meantime, it does allow a splash color to some mono-colored commanders, which is quite big - for example, you can play a Dimir mill deck with Zellix as a commander - for example, this entry from a tournament: https://www.moxfield.com/decks/ZyuMQOagv0mpcZHjYcuh4g

Lifting this restriction allows doing practice games with Forge for something that's close to TLR - for sure, we can add it as a new format too, but that's a lot more complexity vs. this change which literally won't affect anything unless the user actually chooses to make a deck with a background.

**Pull request closed without merging**
