### PR TITLE
Don't transform X shards of UnlessCost before paying

### PR DESCRIPTION
**Pull request by tool4ever**
You can now pay for `Champions of Minas Tirith` trigger with _Rosheen Meanderer_.

### CODE REVIEW

**Comment by Hanmac** [comment]
i updated the fixes, i don't like it when you mix fix commits with bigger changes

**Review by Hanmac — APPROVED** [review]
The Other stuff looks okay, i think?

**Comment by Hanmac** [comment]
@tool4ever while looking at UnlessCost, we might take a look at this one: #1119 for teaching AI what the UnlessCost is about so we could implement better logic for this?

**Comment by tool4ever** [comment]
thanks, I can try looking into that in follow-up

**Pull request merged**
