### PR TITLE
Improve AI logic for Connive / Change of Plans

### PR DESCRIPTION
**Pull request by Agetian**
This can certainly be improved more in the future PRs, but at least the AI will now activate it meaningfully. This is a pretty complex effect (Connive in general, but also the "phase out" part of Change of Plans specifically), and the areas where it's currently lacking is:

- The AI will not ever choose to phase out anything. Not sure what the logic/considerations should be here. This is specific to Change of Plans.
- The AI may activate Connive but then choose to discard only lands. This is a general Connive AI problem, not specific to Change of Plans, but not sure how to improve it yet.

Otherwise, the AI will now correctly choose X and complete the activation of the effect, but it won't consider doing this if its library size is small (currently set to 5 or less).

### CODE REVIEW

**Comment by Hanmac** [comment]
"Connive X" also need some logic for AI:
* Raffine, Scheming Seer: The AI should probably not attack with More Creatures than Cards in the Library?
* Mask of the Schemer: for this i don't know, only attack, if the damage if not lethal, wouldn't kill the AI by drawing?

For Connive in general, can we look into ReplacementList if AI is able to draw at all? i think there is a helper function for this

**Comment by Agetian** [comment]
Added the canDraw check to ConniveAi. The other two things need a bigger intervention in the attack controller, probably a bit more than I can handle at the moment given the time available to me :( Can anyone else please take a look? Did anyone work with the attack controller recently?

**Comment by Hanmac** [comment]
yeah i will try to think about it

for Raffine, Scheming Seer we probably need a better AI Attack logic that when the AI attacks it doesn't kill itself

**Comment by Agetian** [comment]
Alrighty, sounds good! :)

**Pull request merged**
