### PR TITLE
Update to Quest opponent icons list, quests and info

### PR DESCRIPTION
**Pull request by NuWiSan**
Update to the quest opponent icons list for download, that were missing from the list and not present in game, updated info to some existing quests, and update to some icons for more flavor to Duels and Challenges in Zendikar and Urza worlds in Quest mode.

### CODE REVIEW

**Comment by NuWiSan** [comment]
Will work on the missing icons in other worlds and main world

**Comment by tehdiplomat** [comment]
Are all of these icons on the ftp already?

**Comment by NuWiSan** [comment]
Yes. All the icons are already in the ftp, they were only (a lot of them)
out of the list, i copied all the addresses of all the icons from the ftp
and put them back in the list. I would like to add new ones that I created
to have some more variety, but i got no response in discord, or perhaps its
not possible.

Chris H ***@***.***> escreveu (segunda, 4/03/2024 à(s) 15:18):

**Comment by tehdiplomat** [comment]
@NuWiSan Can you start a new thread in Discord and tag me in it? I Don't think i ever saw that one. I can make sure new icons can be uploaded. I don't think that a single opponent can have multiple icons, but i'm sure we'd be glad to have more variation on how things are today. I'll merge this after I fire off the MKM release

**Comment by NuWiSan** [comment]
Started the thread like you told me. By the way the icon images: Spawn of Pogo and Sen-Sei, donwload a empty file from the ftp. Maybe you can erase them from the ftp. After i check the corresponding decks ill see if we need new icons or if we can use some existing ones.

**Review by tehdiplomat — APPROVED** [review]

**Pull request merged**
