### PR TITLE
Kicker Linked Lite

### PR DESCRIPTION
**Pull request by tool4ever**
Fixes cases like this where the kicked creature would copy something else and then have that cost count for the new abilities:
image

### CODE REVIEW

**Comment by Hanmac** [comment]
isUnlinkedAbility is an interesting start

what you also could check is for IsIntrinsic (or something)
while currently nothing should be able to add Kicker to a Card (Except StickerKicker)


does the checks for "cast a kicked spell" still works?

**Comment by Hanmac** [comment]
Especially this one:

>  Rumbling Aftershocks {4}{R}
>  Enchantment
> Whenever you cast a kicked spell, you may have Rumbling Aftershocks deal damage to any target equal to the number of times that spell was kicked.

**Comment by tool4ever** [comment]
yea that still works because (at least for kicker I guess) only if ctb host and the card that's being checked are equal it could be a broken link

**Comment by Hanmac** [comment]
i probably would name the method "isLinkedToCastSA" or something, because when i later try to make Linked Abilities that are linked between an Replacement Effect and a Static Ability i might need another name

**Comment by tool4ever** [comment]
@Hanmac 
anything else needed before merge?

**Review by Hanmac — APPROVED** [review]
👍

**Pull request merged**
