### PR TITLE
Enforce sets in quest

### PR DESCRIPTION
**Pull request by Robbatog**
This PR includes two changes:

1. Enforcing the current world's rules for player decks. `getDeckConformanceProblemsBeforeGame()` runs the deck through the quest's `GameFormat`'s `getPoolLegalityProblem()`, which applies its `filterRules` and also checks for banned/restricted cards. Challenges with custom human decks, such as Tibalt vs Sorin don't need to pass these checks.
2. Add a new Quest Preferences setting that toggles this behavior on and off. Off by default.

Test by:

- Making a new quest with a starting pool of cards from mixed vintage/standard sets. Create a vintage deck. Travel to Alara or Random Standard. Try to run a duel. Should work. Now go to Quest Preferences and change World Rules Conformance to 1. Try to run another duel. Should fail and tell you which cards are illegal.
- **This test will require some hacking in `QuestController.regenerateChallenges()` to force the correct challenges to spawn**. Create a quest with mixed vintage/standard cards, and run a challenge with a fixed human deck. Should be playable regardless of current world and World Conformance Rules setting. Now give it a "normal" challenge. Playability should behave exactly as a regular duel.

### CODE REVIEW

**Comment by Robbatog** [comment]
Note that these changes only affect forge-gui-desktop, and there's only US localization. Does this require addressing before being merged?

**Comment by paulsnoops** [comment]
> Note that these changes only affect forge-gui-desktop, and there's only US localization. Does this require addressing before being merged?

I'd say add the the option in all properties files in English for now. They can be translated later

**Comment by Agetian** [comment]
This seems like a good contribution with a requested fix that's trivial and probably takes 10 minutes to complete. Is the original contributor still available and planning to see the PR through to completion?

**Comment by Robbatog** [comment]
> This seems like a good contribution with a requested fix that's trivial and probably takes 10 minutes to complete. Is the original contributor still available and planning to see the PR through to completion?

Still here. I tried making changes to the language files two weeks ago, but had trouble with their encodings. For example, es-ES.properties is shown as UTF-8-BOM in Notepad++, but ISO-8859-1 in IntelliJ, and changing any line with either of those messes up the entire file. Since then I haven't had time to look into it further. What encodings should be used, and is there a recommended editor for this?

**Comment by paulsnoops** [comment]
> 

In IntelliJ try this: File > Settings > Editor > File Encodings > Properties Files (.*properties) > UTF-8

I'm sure this worked for me when I had the same issue, maybe try UTF-8 for global and project encoding too if that alone doesn't work. Hope this helps!

**Review by Agetian — APPROVED** [review]

**Pull request merged**
