### PR TITLE
707.10: Copied spells incomplete

### PR DESCRIPTION
**Pull request by tool4ever**
Some paid costs are not copied / can't be found.

E.g. copying an evoked _Mulldrifter_ with _Lithoform Engine_ - the copy sacrifice won't trigger.

### CODE REVIEW

**Comment by Hanmac** [comment]
* getCopiedPermanent is wrong there, because this is also set for token copies which should never have this. It is also set for Clones which causes other problems too.
* setCopiedSpell is reset to `false` before is token is set
* `copySpellHost` should probably just set the CastSA for the copy

**Comment by tool4ever** [comment]
Thanks for the feedback 👍 

Initial tests seem promising.

I've also been able to fix the following:
- Copy of _Endless One_ with _Double Major_ not gaining counters
- _Altered Ego_ copying _Gadwick_ letting you draw cards from ETB trigger (got broken a while ago)

**Comment by tool4ever** [comment]
Fixed _Ashling the Pilgrim_ equipped with _Illusionist's Bracers_ not counting the copies

707.10b A copy of an ability has the same source as the original ability. If the ability refers to its
source by name, the copy refers to that same object and not to any other object with the same
name. The copy is considered to be the same ability by effects that count how many times that
ability has resolved during the turn.

**Comment by Hanmac** [comment]
have you checked `Mana Spent this way` effects? i think they currently check for CastSA ?

**Comment by tool4ever** [comment]
> have you checked `Mana Spent this way` effects? i think they currently check for CastSA ?

Fixed

**Review by Hanmac — APPROVED** [review]
i might change OriginalAbility in the Future, but for now i think it should work

**Pull request merged**
