### PR TITLE
150 sleeves

### PR DESCRIPTION
**Pull request by ChristiamMB**
hello, 
I would like to add 150 sleeves, I have already tested it on my forge and it works fine.

### CODE REVIEW

**Comment by Hanmac** [comment]
@tehdiplomat imo is that too much for the default package?

**Comment by tehdiplomat** [comment]
Yea 50 megs is probably too big. I think we should figure out how to make this downloadable

**Comment by tool4ever** [comment]
hopefully not all of these are Arena assets?
Those should be excluded at least imo

**Comment by ChristiamMB** [comment]
Hi, sorry, I uploaded the unoptimised one which weighs 50mb, I'm going to upload the 15mb one which is optimised.

**Comment by ChristiamMB** [comment]
@tool4ever you mean remove those that are Arena assets?

**Comment by tehdiplomat** [comment]
Right Arena assets should not be in our repo

**Comment by ChristiamMB** [comment]
No problem, I'll modify it and upload it again.

**Pull request closed without merging**
