### PR TITLE
Fix Slogurk not triggering when dying from SBA legendary

### PR DESCRIPTION
**Pull request by tool4ever**
Is there anything we can test that this might break?

### CODE REVIEW

**Comment by Hanmac** [comment]
wasn't that fixed before or did it break again?

**Comment by tool4ever** [comment]
Hmn, I don't think it was fixed

Here's my state for testing:
just cast the shock and choose to keep the older one
[!SLOGURK.txt](https://github.com/Card-Forge/forge/files/8646758/SLOGURK.txt)

**Comment by Hanmac** [comment]
@Agetian can you debug it if there is a better way?

**Comment by Agetian** [comment]
Ugh probably this is not my zone of comfort when it comes to debugging things, but I'll see if I can take a look

**Comment by Hanmac** [comment]
@tool4ever i thought the problem was fixed in the old repository, but maybe that wasn't merged there

**Pull request merged**
