### PR TITLE
TriggeredAttacker corrections

### PR DESCRIPTION
**Pull request by Fulgur14**

### CODE REVIEW

**Comment by Hanmac** [comment]
@tool4ever shouldn't this be `TriggeredAttackerLKICopy`?

**Comment by tool4ever** [comment]
yea

**Comment by Hanmac** [comment]
@tool4ever about these `DB$ Destroy | Defined$ Self | Sacrifice$ True` cards like Ordeal, can we try to rewrite them using Sacrifice Effect instead of Destroy Effect? 

imo it feels wrong if the Destroy Effect doesn't Destroy (See also #5713 )

**Comment by tool4ever** [comment]
ugh, I'd have to check but I'm not sure if that requires switching some engine parts around too?

**Comment by Hanmac** [comment]
> ugh, I'd have to check but I'm not sure if that requires switching some engine parts around too?

i don't think that should be needed, `Sacrifice | Defined$ Self` should already work?

**Review by tool4ever — APPROVED** [review]

**Pull request merged**
