### PR TITLE
Fix Revival Experiment via handlePaid cleanup

### PR DESCRIPTION
**Pull request by tool4ever**

### CODE REVIEW

**Comment by Hanmac** [comment]
whats with RememberedAmount and why aren't the Players counted too?

was that a breaking change before?

**Comment by tool4ever** [comment]
We still have `Count$RememberedSize` if we need to know about both

Otherwise it makes sense to have it only look at Cards
(For players we still have `PlayerCountRemembered)
`
Because the syntax was wrong on scripts like _Molten Psyche_ the calculation didn't get messed up

**Comment by Hanmac** [comment]
i mean it more a long time ago it might have been done different, that's why the scripts needed Minus1?

**Comment by tool4ever** [comment]
Yea, if it wasn't a plain bug a long time ago at least

**Review by kevlahnota — APPROVED** [review]

**Pull request merged**
