### PR TITLE
Plane types to TypeList.txt

### PR DESCRIPTION
**Pull request by Simisays**
Don't know if this is needed for now but might be usefull in the future ?

### CODE REVIEW

**Comment by Hanmac** [comment]
Technically "Planar Types"

For the others I need to debug the multiword lists or if we can cheat it somehow

**Comment by Hanmac** [comment]
@tehdiplomat can this merged for now? i want to tune it later for multiword

**Comment by tehdiplomat** [comment]
Fine with me

**Review by Hanmac — APPROVED** [review]
👍

**Pull request merged**
