### PR TITLE
Update Modern Horizons 3.txt

### PR DESCRIPTION
**Pull request by Glorax**

### CODE REVIEW

**Comment by paulsnoops** [comment]
Are you doing this manually? Just asking because we run a script once a day to update edition files

**Review by paulsnoops — APPROVED** [review]

**Comment by Glorax** [comment]
Yes, I have been. I didn't realize it was so simple as running a script. Here I thought I was saving other people time.

**Comment by paulsnoops** [comment]
The last update didn't remove anything, it did adjust some artist names though: https://github.com/Card-Forge/forge/pull/5274/files

It's no problem at all you doing it manually I just thought I'd mention it to save you some time, it pulls from Scryfall though so it won't add leaked cards until they're on the site so they'd have to be manual

**Comment by Glorax** [comment]
It was a while ago that some things got removed. I'm just going to let it pull from Scryfall from now on.

**Pull request merged**
