### PR TITLE
only reset castFaceDown when making a full spell copy

### PR DESCRIPTION
**Pull request by tool4ever**
image

sa.copy does reset it for copied spells

### CODE REVIEW

**Comment by Hanmac** [comment]
imo shouldn't this property be copied too?

**Comment by tool4ever** [comment]
@Hanmac 
I checked CR, when making full copies it should only see face-down characteristic so it doesn't have another front for that status

It's also needed so this works:
> If Ertai’s Meddling is used to copy a spell being cast face down due to Morph ability, the spell will create a face up, 2/2, colorless, nameless creature with no text. This may be a little counter-intuitive, because you might expect the card to enter the battlefield face down like it would have when originally cast, but Ertai’s Meddling copies only the original spell and not the entire card the spell represented.

**Comment by tool4ever** [comment]
Yea I think so

**Comment by Hanmac** [comment]
Question: this does exile with counters on them, it shouldn't put the counters on it later.

(if there is a difference)

**Comment by tool4ever** [comment]
Right, I also couldn't think of a card where it matters (yet)

But I've added it just in case

**Comment by tool4ever** [comment]
Hmn, there's _Evelyn_ or _Ranar_ 
But I didn't find a case where it might matter here

**Comment by kevlahnota** [comment]
this looks good, gonna merge it

**Pull request merged**
