### PR TITLE
Playable Leonin Update

### PR DESCRIPTION
**Pull request by EldritchBimbo**
Adds:
.Playable Leonin race at parity with other options. (2 animation sets, 20 portraits.)

Changes:
.Adds new portraits to avatar .png.
.Edits avatar.atlas and heroes.json to accommodate new options.

### CODE REVIEW

**Comment by Simisays** [comment]
Looks cool ! though it seems like the ears are clipping out during the walk animation or is this intended ?

**Comment by EldritchBimbo** [comment]
I'd have to double-check, is it happening with the male, female, or both
sprites?

**Comment by Simisays** [comment]
@EldritchBimbo 

https://user-images.githubusercontent.com/67333662/233678687-321e68f4-415e-48f6-8bdd-4ed1cb5a98a1.mp4

I've made a small vid look at the top end of the head

**Comment by EldritchBimbo** [comment]
Ah. That's expected behaviour, the pixel of outlining on top of the ears goes out of frame in the one where she jumps. I figured it wasn't noticeable enough to be an issue (other sprites I've made do this and no one's called attention to it to my knowledge?) but my perception might be skewed since I play primarily on mobile. I can take it in for a rework if you think it's too glaring, I'd probably have to either cut the jump or shorten the ears though, which I'd rather not. Do you think it's too visible?

**Comment by Simisays** [comment]
@EldritchBimbo Nah it's fine ! I've just become very good at quickly finding sprites clipping since I've added so many of them ha

**Review by Simisays — APPROVED** [review]

**Comment by EldritchBimbo** [comment]
Hehe, fair enough! Appreciate you pointing it out ^^

**Pull request merged**
