### PR TITLE
refactor aideck selection

### PR DESCRIPTION
**Pull request by kevlahnota**

### CODE REVIEW

**Comment by Hanmac** [comment]
@Agetian need to check if it works on android

**Comment by kevlahnota** [comment]
@Agetian already tested on Android 11 & Android 12, need to test at least Android 10 I think or maybe Android 8

**Comment by Agetian** [comment]
Seems to work fine on Android 10, sadly, I don't have an Android 8 device anymore to test on :/

**Comment by kevlahnota** [comment]
gonna commit, seems to work fine on Android 8 as well

**Pull request merged**
