### PR TITLE
Adventure: check for decks in user plane directory too

### PR DESCRIPTION
**Pull request by Jorilx**
Hi everyone,
I've noticed that when using a user plane (from `USER_ADVENTURE_DIR/userplanes`) Forge looks for decks only under "common", so I've made this simple patch to make it look under the user plane directory too.

### CODE REVIEW

**Review by jjayers99 — CHANGES_REQUESTED** [review]
It's a small observation, but considering how rarely user planes see use at this time, I would prefer to confirm that a custom plane is configured before making the file system call to check for deckfile.exists() and the same with any other references that check for custom / overriden data in this way.

Of more relevant note, this change should be expanded to encompass ".json" formatted files which are loaded a few lines below.

**Comment by Jorilx** [comment]
Ok, I'll update the PR ASAP, thanks for your suggestion!

**Comment by Jorilx** [comment]
I've studied the code better, [this line](https://github.com/Card-Forge/forge/blob/08b8d7deecc127053fef1e2006b1ff69ad3d43d0/forge-gui-mobile/src/forge/adventure/util/CardUtil.java#L680) 
`FileHandle handle = Config.instance().getFile(path);`
already handles the userplane-or-common cases, so my patch can be simplified a lot... I'll update the PR in a few minutes.

**Comment by Jorilx** [comment]
I think the new patch looks nicer, but in the end the code still performs the file system checks... I'll try modifying `Config.getFile()`

**Comment by jjayers99** [comment]
What you have here should be fine

**Review by jjayers99 — APPROVED** [review]

**Comment by Agetian** [comment]
Please rebase against the current upstream master branch so that this PR can be merged.

**Pull request merged**
