### PR TITLE
ETB update: Java code, adventure custom cards, token scripts

### PR DESCRIPTION
**Pull request by dracontes**
Changing "enters the battlefield" to "enters" (and the respective variants of the first to the variants of the second) as detailed on Gatherer where it's functionally relevant. Items that were ignored:
- Code comments
- Language/translation files
- Puzzle and deck descriptions

I hope my tinkering with the code is at least useful to start off. I do feel as some strings for look-up get rather short, maybe some internal keywording would be more useful in the long term.

**Edit 30-07-2024:** As requested by Hanmac, replaced keyworded ETB tapped replacement effects with the code that would be generated by the game engine. Split the difference on `As it enters` collapsing onto the aforementioned replacement effects mostly for clarity.

**Edit 04-08-2024:** Setting to draft and splitting this PR off into more focused ones.

### CODE REVIEW

**Comment by tool4ever** [comment]
Unfortunately we haven't gotten around to refactoring that tapped RE without keyword
this means all of these PR will have to be merged really close together, otherwise only updated scripts would work :/

**Comment by Hanmac** [comment]
one thing to notice, for cards like "Uncharted Haven" with:
> Uncharted Haven enters tapped. As it enters, choose a color.

these still needs to be two replacement effects

**Comment by Hanmac** [comment]
> Unfortunately we haven't gotten around to refactoring that tapped RE without keyword this means all of these PR will have to be merged really close together, otherwise only updated scripts would work :/

yeah, these "fake" ETB keywords are on my hit list to remove if able

especially #210

**Comment by Jetz72** [comment]
Could the RE temporarily be reworked to use either wording? You might even leave it that way for a while, since it'd also be a breaking change for custom sets.

**Comment by Hanmac** [comment]
@dracontes @tool4ever @tehdiplomat your opinion of using the change and replace `K:CARDNAME enters tapped.` with a Replacement Effect?

**Comment by dracontes** [comment]
> these still needs to be two replacement effects

In regard to the `SpellDescription$` for the choose-a-color replacement effect: do I follow the letter of the cards ("`As it enters`") or do I keep it "`As CARDNAME enters`"? Unfortunately, I didn't get around to addressing this conundrum. Fortunately there are no relevant cards in the 'a' folder so I'm well in time to do so.

**Comment by dracontes** [comment]
> @dracontes your opinion of using the change and replace `K:CARDNAME enters tapped.` with a Replacement Effect?

I'd certainly go for something like `K:ETBReplacement:Tapped`. Looking over scripts it seems like we have a good starting point for paring down in, say, Razorverge Thicket's version (<https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/r/razorverge_thicket.txt>).

**Comment by Hanmac** [comment]
> > @dracontes your opinion of using the change and replace `K:CARDNAME enters tapped.` with a Replacement Effect?
> 
> I'd certainly go for something like `K:ETBReplacement:Tapped`. Looking over scripts it seems like we have a good starting point for paring down in, say, Razorverge Thicket's version (https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/r/razorverge_thicket.txt).

Something like ETBReplacement is just a short fix, this one is on my hit-list too


So I think `K:CARDNAME enters tapped.` should be replaced with this:
```
Event$ Moved | ValidCard$ Card.Self | Destination$ Battlefield | ReplacementResult$ Updated | ReplaceWith$ ETBTapped | Description$ CARDNAME enters tapped.
SVar:ETBTapped:DB$ Tap | Defined$ Self | ETB$ True
```

@tool4ever your opinion?

**Comment by tool4ever** [comment]
Ideally and eventually yes
There are probably a few that can then be swapped to NICKNAME too

**Comment by dracontes** [comment]
> In regard to the `SpellDescription$` for the choose-a-color replacement effect

Had a look and it turns out cards and card faces like [Apex Observatory](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=642482), [Sunken Citadel](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=637010), [Mirage Mesa](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=655203) and [Tarnation Vista](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=660326), already collapsed an ETB choice replacement effect into the same paragraph as the ETB tapped one. Among these only Mirage Mesa keeps the replacement effects separate, apparently the correct interpretation.

**Comment by dracontes** [comment]
Well, `\cardsfolder` is fully uploaded. Regarding this PR should I split off what seems to me to be less questionable: `\adventure\common\custom_cards` and `\tokenscripts`? Also, is it worthwhile to bring `AiController.java` up to speed?

**Comment by Hanmac** [comment]
> Well, `\cardsfolder` is fully uploaded. Regarding this PR should I split off what seems to me to be less questionable: `\adventure\common\custom_cards` and `\tokenscripts`? Also, is it worthwhile to bring `AiController.java` up to speed?

first i would do the custom_cards and the tokenscripts

for the AIController thing, should be separate MR

**Pull request closed without merging**
