### PR TITLE
Edition updates: MB2, SLD, YBLB

### PR DESCRIPTION
**Pull request by paulsnoops**

### CODE REVIEW

**Comment by Hanmac** [comment]
@paulsnoops @tehdiplomat shouldn't MLB be marked as "Fun" because of the Playtest cards?

**Comment by paulsnoops** [comment]
> @paulsnoops @tehdiplomat shouldn't MLB be marked as "Fun" because of the Playtest cards?

It's supposed to be a draft set but I forgot to mark those cards with F in the collector number, will fix now

**Comment by Hanmac** [comment]
@paulsnoops also isn't the Collector Number wrong? Doesn't they start with 999-Text?

https://scryfall.com/card/mb2/999-AC/avacyns-collar-the-symbol-of-her-church

**Comment by paulsnoops** [comment]
Yeah but for now we don't support -XXX in collector numbers

**Pull request merged**
