### PR TITLE
YSNC: Celestial Vault and support

### LINKED ISSUE #777: Celestial Vault

### PR DESCRIPTION
**Pull request by Northmoc**
- closes #777 

I have wondered if Draft stuff should start in None zone, then go to Hand, THEN go to the zone specified by cards like this

Stinking digital-only no CR support :(

### CODE REVIEW

**Review by Suthro — APPROVED** [review]
Though I can't parse the internal java work as well as other reviewers, the Vault script itself looks good and polished to me! Thanks for looping me in

**Comment by tool4ever** [comment]
> I have wondered if Draft stuff should start in None zone, then go to Hand, THEN go to the zone specified by cards like this
> 
> Stinking digital-only no CR support :(

🤷  👍

**Comment by Agetian** [comment]
Is this PR now ready? Looks good to me...

**Comment by Northmoc** [comment]
> Is this PR now ready? Looks good to me...

Yeah, I think it's fine. Tough trying to be very rulesy about the digital stuff as some of their interactions and rules haven't been added to the MtG CR

**Pull request merged**
