### PR TITLE
Prototype rollback fix

### PR DESCRIPTION
**Pull request by tool4ever**

### CODE REVIEW

**Comment by Hanmac** [comment]
for the `When is put into your graveyard from the battlefield` how does this work if it was controlled by opponent? does it still trigger for he owner?

it shouldn't use LKI, but it should be an "enter the graveyard" trigger?

**Comment by tool4ever** [comment]
Well the cards have rulings like this:

> If you control an Enigma Sphinx that’s owned by another player, it’s put into that player’s graveyard from the battlefield, so Enigma Sphinx’s middle ability won’t trigger. 

so this gets fixed

**Comment by tool4ever** [comment]
Looks like it should also use LKI anyway:

> 603.10a. Some zone-change triggers look back in time. These are leaves-the-battlefield abilities

\+

> 603.6c. Leaves-the-battlefield abilities trigger when a permanent moves from the battlefield to another zone, or when a phased-in permanent leaves the game because its owner leaves the game. These are written as, but aren't limited to, "When [this object] leaves the battlefield, . . ." or "**Whenever [something] is put into a graveyard from the battlefield, . . . .**"

**Comment by Hanmac** [comment]
> Looks like it should also use LKI anyway:
> 
> > 603.10a. Some zone-change triggers look back in time. These are leaves-the-battlefield abilities
> 
> +
> 
> > 603.6c. Leaves-the-battlefield abilities trigger when a permanent moves from the battlefield to another zone, or when a phased-in permanent leaves the game because its owner leaves the game. These are written as, but aren't limited to, "When [this object] leaves the battlefield, . . ." or "**Whenever [something] is put into a graveyard from the battlefield, . . . .**"

So it is still a Die / Leave the Battlefield trigger and not a "Enter the Graveyard" ? This is important for Clone effects

i mean this is probably good for now, but i still ask some judges too

**Pull request merged**
