### PR TITLE
Fix unmorphing being prevented by invalid static

### PR DESCRIPTION
**Pull request by tool4ever**
You should be allowed to turn _Lumithread Field_ face up with _Humility_ in play.

### CODE REVIEW

**Comment by Hanmac** [comment]
what kind of keywords needed to be cleaned there?

**Comment by tool4ever** [comment]
The one from Humility because its LKI copy

**Comment by Hanmac** [comment]
> The one from Humility because its LKI copy

but that doesn't make any sense, i mean Humility doesn't use any keyword?
Ah, its the `remove all abilities` that needs to be cleaned, right?

**Review by Hanmac — APPROVED** [review]
👍

**Comment by tool4ever** [comment]
> > The one from Humility because its LKI copy
> 
> but that doesn't make any sense, i mean Humility doesn't use any keyword? Ah, its the `remove all abilities` that needs to be cleaned, right?

Yea

**Pull request merged**
