### PR TITLE
Keyword: Spree

### LINKED ISSUE #4813: Keyword: Spree
maybe combine a Charm Effect with an Additional Cost Effect that adds more Cost depending on the Charm Choices?

> Spree (Choose one or more additional costs.)
+{2} —Exchange control of two target creatures
+{1} —Exchange control of two target artifacts
+{1} —Exchange control of two target enchantments

### PR DESCRIPTION
**Pull request by Hanmac**
Closes #4813 

i think it is already functional?

it might just need some GUI love for the generated Charm Description

### CODE REVIEW

**Review by Agetian — APPROVED** [review]

**Comment by Agetian** [comment]
Looks good, yeah!

**Comment by Hanmac** [comment]
@tool4ever should we try to update the Description now, or should that be later?

**Comment by tool4ever** [comment]
I could check for it soon

**Comment by Hanmac** [comment]
@tool4ever in `CharmEffect::makeFormatedDescription` check for `Spree$ True`
and then use this to also check for SpreeCost on the Options

**Comment by tool4ever** [comment]
image

**Comment by Hanmac** [comment]
the only difference might be to have Spree line rendered instead of the "Choose one or more" line (in the CharmEffect)

the difference would be that it wouldn't have an extra empty line i think

**Review by tool4ever — APPROVED** [review]

**Pull request merged**
