### PR TITLE
LastState: pass through from GameAction into ReplacementHandler & performance fixes

### PR DESCRIPTION
**Pull request by tool4ever**
1. Fixes _Giada, Font of Hope_:
if multiple angels ETB together they don't see each other

2. I noticed cases where StaticAbilityContinuous kept checking stuff, even if there was nothing to affect.
E. g. _Heroes' Podium_ if you control no legendary creature it would still call into `AbilityUtils.calculateAmount` and then still deeper into `CardProperty`

### CODE REVIEW

**Comment by Hanmac** [comment]
Test for you
Have the Orzhov angel that exiles opponent dying exiled by brutal cathar or other "exile until cardname leaves the battlefield"
Have also a few other creature on the field 
Then do a board wipe

The others shouldn't be exiled by the returning angel

**Comment by tool4ever** [comment]
Depending on the destroy order some will get exiled :/

But doesn't work on master either

I'll see if I can find a clean fix for it

**Comment by Hanmac** [comment]
> Depending on the destroy order some will get exiled :/
> 
> But doesn't work on master either
> 
> I'll see if I can find a clean fix for it

yeah that is probably a different issue, regarding LTB instead of ETB

**Comment by Hanmac** [comment]
i have an idea to use LTB Replacement effects of the LKIs, but that can be done after this MR

**Pull request merged**
