### PR TITLE
Blitz Again, check for Keyword

### PR DESCRIPTION
**Pull request by Hanmac**
@Agetian @tool4ever 

This is for Blitz only triggering when the specific cost was paid (for this Reference to Keyword)

But there is a corner case i couldn't get working:

* Toolbox on the Field
* Cast Hill Giant with Blitz
* while on the Stack, copy the Blitz Hill Giant with Double Major
* Currently the token doesn't get Haste and trigger because the condition does fail.

but i can't find it at what place from copying the Spell, the Spell gaining Blitz on the Stack again (for this i copied the KW so the ability should give it the new one?) til the creature entering the battlefield.

somewhere i get the wrong static ability with a different keyword instance

can some one of you debug it?

### CODE REVIEW

**Comment by Hanmac** [comment]
@tool4ever can you try to debug my problem if able

**Comment by tool4ever** [comment]
Yea might be a few more days till I have enough time for it

**Comment by tool4ever** [comment]
@Hanmac 
If I change the `this` into `result` for `copy.setKeyword` it works...?

**Comment by Hanmac** [comment]
> @Hanmac If I change the `this` into `result` for `copy.setKeyword` it works...?

thanks for finding it!

**Review by tool4ever — APPROVED** [review]

**Pull request merged**
