### PR TITLE
AI Pump tweaks for abilities with a sacrifice self cost + Witch's Clinic AI hint.

### PR DESCRIPTION
**Pull request by Agetian**

### CODE REVIEW

**Comment by Hanmac** [comment]
@Agetian you probably need to rebase your MR ?

**Comment by Agetian** [comment]
Hmm, that's what I did, and it ended up in this weird state :/

**Comment by Agetian** [comment]
Ok, second time's the charm :D

**Comment by Hanmac** [comment]
my main concern with "Witch's Clinic", why does AI want to give my Creatures (or even non Creatures?) Lifelink?

shouldn't that be better handled with the Pump Logic?

**Comment by Agetian** [comment]
> my main concern with "Witch's Clinic", why does AI want to give my Creatures (or even non Creatures?) Lifelink?
> shouldn't that be better handled with the Pump Logic?

Most likely yes, but it'll most likely involve a custom AI logic of some sort anyway, since it doesn't go through the regular "Curse / non-Curse" path which is used for creatures. At first I thought about extending that logic for basically everything, but can't quite figure out what the repercussions would be for other potential cards (where non-creatures are pumped), since Pump has a really wide variety of use cases for non-creatures :/

**Review by tool4ever — APPROVED** [review]
seems ok, some people would complain if we'd limit the Clinic to creatures only anyway ;)

**Pull request merged**
