### PR TITLE
Fix Ivy checking targets with wrong player

### LINKED ISSUE #2424: Ivy Copy and other Each Can Target
https://github.com/Card-Forge/forge/blob/154cc84d5c94acb64bcbc0e77252fd20adc2c08f/forge-game/src/main/java/forge/game/ability/effects/CopySpellAbilityEffect.java#L96-L108

its about the Line of candidates, it should try to make a copy first controlled by the new controller to see if the candidate can be targeted by the new copy. OR just an LKI copy with changed controller

the corner case are spells (and auras) that restrict what they can target depending on the controller ("creature you control")

### PR DESCRIPTION
**Pull request by tool4ever**
Closes #2424

### CODE REVIEW

**Comment by Hanmac** [comment]
no it should always copy for controller
that's why we might want to use lki

**Comment by tool4ever** [comment]
> no it should always copy for controller that's why we might want to use lki

that's not what "could target" usually means

> Even though you control the copies, the ability cares about who cast the original spell when determining which other creatures that spell could target. If the original spell has a targeting restriction that refers to “an opponent,” the copies will see that from the perspective of the original spell’s controller. For example, if your opponent casts a spell that says “Destroy target creature an opponent controls” targeting your Ink-Treader Nephilim, its ability will create a copy for each other creature the original spell could target: the rest of your creatures. However, since you control the copies, all the copies won’t resolve for having illegal targets.

**Comment by Hanmac** [comment]
does your part has a Rules Number from CR? i think the Ruling for  Ink-Treader Nephilim might be outdated

but Ivy says:
> If Ivy, Gleeful Spellthief isn’t a legal target for the spell, no copy can be created.

so in case for `Ivy, Gleeful Spellthief` does it mean legal target before or after you copy and gain control of the spell?

* Ivy says that if she can't be the copy, no spell is created
* Ink-Treader Nephilim says, that the copies are created, but don't resolve because of illegal target (meaning the spell with illegal targets are created?)

**Comment by tool4ever** [comment]
This is what CopyForEachCanTarget$ is originally written for:

> 707.10d. Some effects copy a spell or ability for each player or object it "could target." The copies are put onto the stack with those targets in the order of their controller's choice. If the spell or ability has more than one target, each of its targets must be the same player or object. If that player or object isn't a legal target for each instance of the word "target," a copy isn't created for that player or object.

Ivy is different template, it should be this:

> 707.10e. Some effects copy a spell or ability and specify a new target for the copy. If the spell or ability has more than one target, each of the copy's targets must be that player or object. If that player or object isn't a legal target for each instance of the word "target," the copy isn't created.

**Comment by Hanmac** [comment]
i talked with more Judges, yes Ivy and the other "this spell could target" stuff are different

this also means that i would something like "TargetDefined$ Self" for Ivy and don't touch the "Can be Targeted By This Spell" where you can do the logic about making sure that the new copy can target ivy while the new spell is controlled by you

**Review by Hanmac — DISMISSED** [review]
👍

**Pull request merged**
