### PR TITLE
Support for  Midnight Crusader Shuttle

### LINKED ISSUE #4323: AI can target player with hexproof
**Describe the bug**
AI targets player with hexproof by first ability of Relic of Progenitus. Ability of Relic of Progenitus fizzles, but AI shouldn't even have to target a player with hexproof.

**To Reproduce**
1. AI casts Relic of Progenitus.
2. Player has Shalai, Voice of Plenty
3. AI activates first ability of Relic of Progenitus and targets player
4. First ability of Relic of Progenitus fizzles.

**Expected behavior**
AI can't targets player with hexproof.

**Desktop**
OS: Windows 10
Java Version: 1.8.0_202-b08
Forge Version: 1.6.60-SNAPSHOT-12.06

**Screenshots**

relic

### PR DESCRIPTION
**Pull request by tool4ever**
Had to clean the logic for this

Closes #4323

### CODE REVIEW

**Comment by Hanmac** [comment]
@tool4ever you probably should try to do the Midnight Crusader yourself

The ControlGain Effect needs a way to Remember if the GainControl was successful

(there are some cards that prevents the Control from being switched)

**Comment by tool4ever** [comment]
I'm aware of that and as the name implies the param RememberControlled$ works this way already

**Comment by Hanmac** [comment]
> RememberControlled

huch for some reason i couldn't find it when i searched

**Comment by Hanmac** [comment]
@tool4ever can you remove the HiddenKeywords from ControlGainEffect ?
the part where it checks for HIDDEN inside AddKWs

a small search shows that they are not used anymore? or I'm wrong?

**Comment by tool4ever** [comment]
yes less dirty mixup

**Review by Hanmac — APPROVED** [review]

**Pull request merged**
