### PR TITLE
update Phyrexian designation code

### PR DESCRIPTION
**Pull request by kevlahnota**
- #5693 to support Bloomburrow Pawprint {P} designation

### CODE REVIEW

**Comment by tehdiplomat** [comment]
Looks like you have a failing test. It seems like you updated that file, so maybe a toString needs to updated that wasn;t?

**Comment by kevlahnota** [comment]
> Looks like you have a failing test. It seems like you updated that file, so maybe a toString needs to updated that wasn;t?

fixed

**Comment by Hanmac** [comment]
@kevlahnota commando back

All the other still uses WP or something

It's only about exactly "{P}" used for Rage Extractor

**Comment by kevlahnota** [comment]
> @kevlahnota commando back
> 
> All the other still uses WP or something
> 
> It's only about exactly "{P}" used for Rage Extractor

I can rollback and only replace the single P to use H, what's your final take on this @tehdiplomat

**Comment by kevlahnota** [comment]
need to wait for final ruling update...

**Comment by Hanmac** [comment]
> need to wait for final ruling update...

No need to close it, my sources say it's only one icon
(And even if not, we can do the other ones later)

**Comment by Agetian** [comment]
Will reopen for now, it's definitely workable and can be updated promptly once we have information.

**Comment by kevlahnota** [comment]
> Will reopen for now, it's definitely workable and can be updated promptly once we have information.

gonna close this, since pawprint are not really related to manashards, its only GUI display, gonna close this and push a new PR

**Pull request closed without merging**
