### PR TITLE
Formats/premodern update banlist

### PR DESCRIPTION
**Pull request by leriomaggio**
This PR mainly includes a quick FIX to the Premodern Format file to update the Banned List as per yesterday's announcement: 
https://premodernmagic.com/blog/ban-list-update-2023/

**note**: There is also a change to the EN translation file for a new label (i.e. "Random Premodern Archetype Generator") This comes from another (internal) branch where this was forked from, and won't affect anything in the rest of the code.

So I thought I could leave it there, as this will be integrated in my next upcoming PR :)

### CODE REVIEW

**Review by tool4ever — CHANGES_REQUESTED** [review]
Your branch seems to start on some already rolled back changes, please rebase without any old commits

**Comment by leriomaggio** [comment]
> Your branch seems to start on some already rolled back changes, please rebase without any old commits

I rebased the branch to `upstream/master`.  Is this what you meant ? 
if not, I will redo everythng again,  by forking from `origin/master` and not from another branch I was working on. 

Cheers.

**Comment by tool4ever** [comment]
Well if you check the commits tab you will see that they're still there
So all your branches probably need to drop other authors work that's not on upstream

**Comment by leriomaggio** [comment]
> Well if you check the commits tab you will see that they're still there So all your branches probably need to drop other authors work that's not on upstream

Ah sorry, I see now what you mean. 

Tbh, I simply synced with `upstream/master` so I genuinely don't know how I ended up like that. 

Will redo the PR then. It's quicker.

**Comment by leriomaggio** [comment]
Opened new PR on #3481

**Pull request closed without merging**
