### PR TITLE
Update Mobile Build

### PR DESCRIPTION
**Pull request by kevlahnota**
- Android libs to 8.0.0
- LibGDX libs to 1.12.1

### CODE REVIEW

**Comment by Agetian** [comment]
Tested it on my Linux system, seems to work alright for the purpose of building and running via mobile-dev in a Linux environment. Sadly, can't really test the Android build as such, as I don't have a working dev environment configured to build Android snapshots... I wasn't very successful in setting one up the last I tried, so hopefully someone else can give it a try on an actual Android device :/

**Comment by Hanmac** [comment]
@Agetian i tested the Android on my system, and it seems to work so far?

**Comment by Agetian** [comment]
Nice, then it should be good to go 👍

**Comment by kevlahnota** [comment]
> Nice, then it should be good to go 👍

I think there's no M1 user or any MacOS on ARM Chip, I guess LibGDX covered this already before [(LWJGL 3.3.0)](https://github.com/libgdx/libgdx/pull/6721), @tehdiplomat can you check if the PR can be built by the Github Actions? I don't think there is anymore changes beside updating the Sentry dependency on another PR.

**Comment by Hanmac** [comment]
@kevlahnota and after this gets merged, I will try to do my Android Manifest update again

**Comment by kevlahnota** [comment]
> @kevlahnota and after this gets merged, I will try to do my Android Manifest update again

the manifest merger works as long as the new modified android maven plugin is used -https://github.com/Card-Forge/android-maven-plugin/pull/1, on my local build I use this and it generates a new androidmanifest.xml with the updated version name and version code 
```
<executions>
	<execution>
		<id>update-manifest</id>
		<goals>
			<goal>manifest-merger</goal>
		</goals>
		<configuration>
			<androidManifestFile>${project.basedir}/AndroidManifest.xml</androidManifestFile>
			<manifestVersionName>${alpha-version}</manifestVersionName>
			<manifestVersionCode>${alpha-versionCode}</manifestVersionCode>
		</configuration>
	</execution>
</executions>
```

**Comment by Hanmac** [comment]
I tried this in my MR, it works because all other stuff are default parameters.

```xml
<executions>
  <execution>
    <id>update-manifest</id>
    <goals>
      <goal>manifest-merger</goal>
    </goals>
    <configuration>
      <manifestVersionCodeUpdateFromVersion>true</manifestVersionCodeUpdateFromVersion>
    </configuration>
  </execution>
</executions>
```

I'm going to update my MR later

**Comment by kevlahnota** [comment]
> or does this needs more tests?

as long as the github actions work for the android build, this should be ready

**Comment by tehdiplomat** [comment]
Sould we merge and kick off manual github action to test? Then revert if it doesn't work? I won't be able to get to anything for at least Sunday

**Comment by Hanmac** [comment]
@kevlahnota @tehdiplomat does this https://github.com/Card-Forge/android-maven-plugin/pull/1 need to be merged first?

**Comment by kevlahnota** [comment]
> @kevlahnota @tehdiplomat does this [Card-Forge/android-maven-plugin#1](https://github.com/Card-Forge/android-maven-plugin/pull/1) need to be merged first? (Also, I still wonder why #mvn install:install-file doesn't work?)

If you need to use manifest merger then it needs to use the new modified android maven plugin

**Comment by Hanmac** [comment]
@kevlahnota we can merge THIS MR first

then if that works, we can update the Android Plugin one
then if that works, I can work on my Manifest Update MR again

**Comment by Hanmac** [comment]
@tehdiplomat i think we should merge this and see what happens

**Comment by tehdiplomat** [comment]
@Hanmac I'm still on vacation. Not back until Monday.

**Pull request merged**
