### PR TITLE
Fix token CMC when copying

### PR DESCRIPTION
**Pull request by tool4ever**
This decade old shortcut would mean turning ordinary tokens into copies with e.g. _Mirrorweave_ would still keep their CMC at 0.

### CODE REVIEW

**Comment by Hanmac** [comment]
Dies this still respect:
> 202.3b The mana value of a transforming double-faced permanent or spell’s back face is calculated as though it had the mana cost of its front face. If a permanent or spell is a copy of the back face of a transforming double-faced card (even if the card representing that copy is itself a double-faced card), the mana value of the copy is 0.

**Comment by tool4ever** [comment]
@Hanmac 
if I understand correctly:
- token from _Helm of the Host_ equipped onto _Blitzwing, Cruel Tormentor_
- token then transforms into _Blitzwing, Adaptive Assailant_
- token should have CMC=0

?

seems this was also broken

**Comment by Hanmac** [comment]
That fix should be for melded too

**Comment by tool4ever** [comment]
Hmn during testing this didn‘t seem necessary?
Because from the rules change you can only make copies that can transform
And if you‘d clone a meld it would put it as Original state which has no mana cost anyway

**Comment by Jetz72** [comment]
Maybe "even if that copy is represented by two other meld cards" refers to a scenario where you have two different melded permanents in play, and one becomes a copy of the other via something like Nanogene Conversion? That rule could really use an example though.

**Comment by tool4ever** [comment]
Yes, but I meant the way the engine handles it iternally when getting a Cloned state it wouldn't run into this path any longer
though I can just future-proof it here for good measure :)

**Review by Hanmac — APPROVED** [review]

**Pull request merged**
