### PR TITLE
Update Eldrazi Sprite

### PR DESCRIPTION
**Pull request by EldritchBimbo**
Adds:
.New sprite and atlas

Changes:
.Edits enemies.json to change eldrazi enemy to new sprite.

### CODE REVIEW

**Comment by kevlahnota** [comment]
What eldrazi enemy is your reference for the sprite art?

**Comment by EldritchBimbo** [comment]
roe-181-broodwarden
bfz-127-barrage-tyrant
ogw-42-cultivator-drone
bfz-92-dominator-drone

It's a combination of elements, primarily from these.

**Comment by Simisays** [comment]
I like the sprite a lot and it's an improvement to the current one for sure. Though I'm mainly looking for a larger 32x eldrazi sprite (not saying you have to do that as well :)

**Comment by EldritchBimbo** [comment]
Oh, I wouldn't mind! I thought about making the replacement one 32x32, but
I didn't want to cause issues in preexisting dungeons that use the current
eldrazi. I don't mind doing a bigger one, is there anything in particular
you wanted it to be based on? (And relatedly, is it meant to be a boss or a
regular enemy?)

**Comment by Simisays** [comment]
I was more thinking of an enemy for the coming Emrakul dungeon that has a size inbetween the "regular" npc sprite and the emrakul boss. Maybe a floating type eldrazi with a bunch of tentacles ? It's supposed to be the elite enemies you need to fight before you encounter emrakul

**Pull request closed without merging**
