### PR TITLE
GameActionUtil: use Multikicker as KeywordExtraCost

### PR DESCRIPTION
**Pull request by Hanmac**
- [x] Multikicker uses new Table
- [x] AI need some more love, i disabled some code, but AI should use new chooseNumberForKeywordCost instead
- [x] some more cleanup the remaining `isAnnouncing("Multikicker")`

### CODE REVIEW

**Review by Agetian — CHANGES_REQUESTED** [review]
Please make sure the AI code is properly updated to support the new format before merging the code. Sadly, I won't be able to help out before August 20-21 or so (out of town, can only look at stuff and maybe meege in some smaller modifications). Overall, nice idea!

**Comment by Hanmac** [comment]
One goal that may be for this MR is to move chooseNumberForKeywordCost more into the SpellAbilityEffectAI parts

so the AI might decide if it really wants to sacrifice something for Casualty, if the Player doesn't have the Mana to pay for the first unless cost

**Comment by Hanmac** [comment]
@tool4ever can you test if the AI is good enough for it to play it with Multikicker if able?

**Comment by tool4ever** [comment]
doesn't seem like it, never casts _Everflowing Chalice_ now :/

**Comment by Hanmac** [comment]
> doesn't seem like it, never casts _Everflowing Chalice_ now :/

fixed AI

**Review by tool4ever — APPROVED** [review]
seems ok, it should really be hooked up earlier in `calculateManaCost` somehow already to avoid potential misplay but this is cleaner for now

**Comment by Hanmac** [comment]
@Agetian can you look more into the AI parts?

or can this be merged?

**Comment by Agetian** [comment]
I'll be back in town in 2-3 days and I'll take a deeper look at it ;) sadly, can't test or assess things before then, I only have my phone with me ... ^^;

**Review by Agetian — APPROVED** [review]

**Comment by Agetian** [comment]
Looks good to me :) I think the commented out parts in the AI can be safely removed

**Review by Agetian — APPROVED** [review]

**Pull request merged**
