### PR TITLE
Fix ConcurrentModificationException

### PR DESCRIPTION
**Pull request by tool4ever**
Imo this method is so rarely called that removing via Iterator seems pointless (vs. readability).

### CODE REVIEW

**Review by Hanmac — APPROVED** [review]
i wish we could use functions like [retainAll](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ArrayList.html#retainAll(java.util.Collection)) to remove old Commanders

**Review by Hanmac — CHANGES_REQUESTED** [review]
@tool4ever setCommanders is only ever called with empty ArrayList ... so how about removing the function and use a new `clearCommanders` instead?

**Review by Hanmac — APPROVED** [review]
I would have defined a `clearCommanders`, but that is fine too

**Comment by Jetz72** [comment]
That was mostly written as one of those "in case anybody needs it later" methods. Seems like a reasonable cut.

**Pull request merged**
