### PR TITLE
Add card previews when drafting from a spellbook

### PR DESCRIPTION
**Pull request by jjayers99**
First commit to repository, totally open to review / revision / rejection if there's potential unintended side effects from this change.

### CODE REVIEW

**Review by kevlahnota — APPROVED** [review]

**Comment by kevlahnota** [comment]
> Already works on master?
> 
> image

didn't check on desktop, but seems to show the card

**Comment by jjayers99** [comment]
> > Already works on master?
> > image
> 
> didn't check on desktop, but seems to show the card

Unless I'm missing something, the current implementation only shows the names of the draftable cards on forge-gui-mobile.

**Comment by kevlahnota** [comment]
> > > Already works on master?
> > > image
> > 
> > 
> > didn't check on desktop, but seems to show the card
> 
> Unless I'm missing something, the current implementation only shows the names of the draftable cards on forge-gui-mobile.

it seems to work here when I test it on gui mobile for drafting a card from a spellbook..
image

image

**Comment by jjayers99** [comment]
Running from forge-gui-mobile, without my changeset, here's what I see when I'm drafting a card. 

image

**Review by kevlahnota — APPROVED** [review]

**Pull request merged**
