### PR TITLE
Update CardFactory CloneStates: fix SetPower and setToughness

### PR DESCRIPTION
**Pull request by Hanmac**
fix around SetPower and setToughness

@tool4ever this should fix the possible NPE, or do you still want to debug why originalState might be null?

### CODE REVIEW

**Review by Agetian — DISMISSED** [review]

**Comment by tool4ever** [comment]
I don't know if it's a problem yet 🤔 
If _Scarab God_ makes a token of _Arcee, Sharpshooter_ should both sides be 4/4 or is it correct if the Vehicle back stays 2/2?

**Comment by Hanmac** [comment]
> I don't know if it's a problem yet thinking If _Scarab God_ makes a token of _Arcee, Sharpshooter_ should both sides be 4/4 or is it correct if the Vehicle back stays 2/2?

i think i need to ask judges for this, imo the Vehicle probably needs to be a 4/4 too

**Comment by Hanmac** [comment]
@tool4ever 
> Hydra17: the modification would apply to both faces of the TDFC, as far as circumstances allow. in the case of the Vehicle, it is black, and will be a 4/4 while animated. but it is not a Zombie

**Comment by Hanmac** [comment]
i needed the Original Card States from `CardFactory.getCard`

**Review by Agetian — APPROVED** [review]

**Review by tool4ever — APPROVED** [review]
Seems to work 👍

**Comment by tool4ever** [comment]
Copied permanent spells don't seem to be able to transform at all, not sure why yet

**Pull request merged**
