### PR TITLE
CMB1 land tokens fix

### PR DESCRIPTION
**Pull request by schnautzr**
- Forest land tokens created by Generated Horizons have "{T}: Add {G}" per rule 305.6.
- Tokens created by Waste Land are land tokens with the land subtype Wastes, which doesn't appear anywhere else yet.

### CODE REVIEW

**Comment by Hanmac** [comment]
@schnautzr "intrinsic ability" for the forest token means the ability is generated by the basic land type

**Comment by schnautzr** [comment]
See rulings for dual lands like Plateau. It has basic land types, but it's not a basic land. Simply having land types that are defined as basic land types gives it the intrinsic abilities.

**Comment by Hanmac** [comment]
> See rulings for dual lands like Plateau. It has basic land types, but it's not a basic land. Simply having land types that are defined as basic land types gives it the intrinsic abilities.

the intrinsic abilities are done by the CardType you don't need to define them via `A:`

**Comment by schnautzr** [comment]
Ah, misunderstood you then. I'll check and see if this is already happening when I get back to my computer.

**Comment by Hanmac** [comment]
as for the Wastes token, Wastes isn't a Land Subtype

**Comment by schnautzr** [comment]
It says "Wastes land token", not "land token named 'Wastes'".

**Comment by Hanmac** [comment]
thats why Testcards are so problematic :P

**Comment by schnautzr** [comment]
Yeah it needs an Oracle revision!

**Pull request closed without merging**
