### PR TITLE
Implemented Card Anikthea, Hand of Erebos

### PR DESCRIPTION
**Pull request by nshcat**
I implemented one of the new CMM cards.

https://scryfall.com/card/cmm/705/anikthea-hand-of-erebos

### CODE REVIEW

**Comment by tool4ever** [comment]
Thanks but this card is in Forge already: #3069

Always check the Projects tab so you can avoid double work

**Comment by nshcat** [comment]
@tool4ever
Hello, I didnt want to open up a new issue since my question is related, but is there a way to ask for permission to implement a new card via the projects? :) AFAICT, "outsiders" cant create projects.

Im mostly interested in trying my hand on "Composer of Spring" from CMM, to get into the project more.

Thanks

**Comment by tool4ever** [comment]
I'm not really sure if it can be done without manual entry at this point
But I just marked it so go ahead :)

**Comment by nshcat** [comment]
@tool4ever 

Thank you for the chance :) If I notice that it's over my head Ill say so ASAP so theres no huge delay.

**Pull request closed without merging**
