### PR TITLE
Impending: use Effect for Last Time counter removed

### LINKED ISSUE #5481: DSK: Impending Keyword
> Impending N—Cost (If you cast this spell for its impending cost, it enters with N time counters and isn’t a creature until the last is removed. At the beginning of your end step, remove a time counter from it.)

Similar to Fading ...
* ETB with Time Counters
* At end step, remove time counter
* StaticAbility(?) that stops it from being a creature while it has time counters? (This also could be a pump Effect with Duration)

### PR DESCRIPTION
**Pull request by Hanmac**
Closes #5481 

This makes Impending use Effect for the "last Time counter removed" trigger to work

### CODE REVIEW

**Comment by tool4ever** [comment]
This is so:
a) it can't lose creature again if a time counter gets added later gain
b) "loses all abilities" doesn't interact with it
?

**Comment by Hanmac** [comment]
> This is so: a) it can't lose creature again if a time counter gets added later gain b) "loses all abilities" doesn't interact with it ?

That's my current understanding of how it should work, yes.


For example if you cast it while Solemnity us on the field, it's just a non Creature forever

**Review by tool4ever — APPROVED** [review]
I wonder if the duration will be "for as long as" (so phasing out should also break it), but that can be checked when CR is updated

**Comment by Hanmac** [comment]
> I wonder if the duration will be "for as long as" (so phasing out should also break it), but that can be checked when CR is updated

I asked if it works like "for as long as" and the answer was no.

Especially because Solemnity would have stopped the Effect from even starting

**Pull request merged**
