### PR TITLE
HBG Double team

### LINKED ISSUE #764: HBG Double team mechanic

### PR DESCRIPTION
**Pull request by Simisays**
I feel like I'm pretty close to getting this mechanic working. The only thing I'm not able to do is add the perpetual ability to both self and the remembered card (I'm able to just get the effect to one of them

Tested around with MadeCardEffect (to add remove abilities). Didn't really work so I restored the file to what is 

-closes #764

### CODE REVIEW

**Comment by Hanmac** [comment]
why remove the stuff in MakeCardEffect ?

**Comment by Simisays** [comment]
> Tested around with MadeCardEffect (to add remove abilities). Didn't really work so I restored the file to what is

Was trying to add param to  remove abilities with MadeCardEffect. Didn't really have succes so I just restored the the original makecardeffect file. 

There should be no changes made in makecardeffect.java

**Comment by Hanmac** [comment]
> > why remove the stuff in MakeCardEffect ?
> 
> Was trying to add param to remove abilities with MadeCardEffect. Didn't really have succes so I just restored the the original makecardeffect file.
> 
> There should be no changes made in makecardeffect.java

check the changes, there are removes for Spellbook stuff

**Comment by Simisays** [comment]
I'm having trouble reversing that file. Just gonna make a new PR

**Pull request closed without merging**
