### PR TITLE
Migrate all remaining JUnit3 tests to TestNG

### PR DESCRIPTION
**Pull request by allentiak**
These were the last tests that use JUnit3...
(All the others use TestNG.)

Affected subprojects: `forge-game`, `forge-gui-desktop`.

After an `mvn clean && mvn test` from the project root, everything seems to work just fine...

### CODE REVIEW

**Comment by Northmoc** [comment]
This stuff is over my head! Hope you don't mind me changing the reviewer list.

Thanks for the PR!

**Comment by allentiak** [comment]
I've just realized I had mistakenly used tabs. I've just converted them to spaces.

**Comment by tehdiplomat** [comment]
@allentiak Can you push an empty commint to see if the test checks run?

**Comment by allentiak** [comment]
Done. All tests pass :-)

**Comment by allentiak** [comment]
@tehdiplomat Please, feel free to ask if you need anything else.

**Review by tehdiplomat — APPROVED** [review]

**Pull request merged**
