### PR TITLE
Further improvement to PeekAndRevealAi (fix AI paying 0 for X)

### PR DESCRIPTION
**Pull request by Agetian**

### CODE REVIEW

**Review by Hanmac — APPROVED** [review]

**Comment by MorihiroS** [comment]
@Agetian, Kozilek's Command is worked well, but AI still casts Portent of Calamity for 1 blue mana

calam1
comm
comm1

**Comment by Agetian** [comment]
Tested again in these specific circumstances, Portent of Calamity doesn't get cast for 0 in my tests. Maybe you're on an outdated snapshot or the changes haven't been compiled in yet?

**Comment by MorihiroS** [comment]
@Agetian, yea, it was not actual forge-java8.exe, my bad. I tests it, all worked!

**Comment by MorihiroS** [comment]
@Agetian, AI did it again with Kozilek's Command: https://github.com/Card-Forge/forge/issues/6390#issuecomment-2452261537

**Comment by Agetian** [comment]
> @Agetian, AI did it again with Kozilek's Command: [#6390 (comment)](https://github.com/Card-Forge/forge/issues/6390#issuecomment-2452261537)

Separate issue, this MR isn't supposed to fix it, as Kozilek's Command doesn't use PeekAndReveal mechanics or AI.

**Pull request merged**
