### PR TITLE
Add cartouches

### PR DESCRIPTION
**Pull request by schnautzr**
Adds the five cartouches to the items spritesheet. Not used yet, but committing to prevent future conflicts.

### CODE REVIEW

**Comment by kevlahnota** [comment]
@Simisays just merged your ` PR https://github.com/Card-Forge/forge/pull/3108, this will conflict

**Comment by Simisays** [comment]
@schnautzr @kevlahnota 

Combined the two itemsheets (I only added a lantern icon for a new equipment)

items

Also add these 3 to the atlas file 

```
UnderworldCookbook
  xy: 304, 960
  size: 16, 16
Conjurer's Mantle
  xy: 144, 448
  size: 16, 16
ZedruuLantern
  xy: 336, 128
  size: 16, 16
```

**Comment by schnautzr** [comment]
Updated both files as per @Simisays's request above.

**Review by Simisays — APPROVED** [review]

**Review by kevlahnota — APPROVED** [review]

**Comment by Agetian** [comment]
The branch still appears to have conflicting files, please correct @schnautzr .

**Comment by schnautzr** [comment]
Only conflicting files I see are the two that were addressed above.

**Comment by Agetian** [comment]
Maybe you need to rebase the branch (sync it to master)? I had this a couple times when I didn't have any apparent conflicting files but Github still insisted that I did, I rebased my branch and it went away.

**Pull request closed without merging**
